### ISSUE TITLE
PHP Deprecated:  Non-static method

### ISSUE THREAD

**Issue by EgorGruzdev** [mnapoli/silly#27]
```
class ScanCommand
{
    // ...

    public function execute($directory)
    {
        $this->scanner->scan($directory);
    }
}

$app->command('process [directory]', ['MyApp\Command\ScanCommand', 'execute']);
```

When you try to use this method of injection are notified:

```
PHP Deprecated:  Non-static method MyApp\Command\ScanCommand::execute() should not be called statically in /vendor/mnapoli/silly/src/Application.php on line 207
```

And it is only with version 1.5.0

Or I do not understand?

**Comment by thecrypticace** [comment]
The documentation says that any _valid_ PHP callable can be used. Since `execute` is not a static method it is not a valid callable.

See https://github.com/mnapoli/silly/blob/master/docs/command-callables.md

This being said, it shouldn't result in a deprecation notice. And this issue revealed two additional bugs. Thanks for the report! PR opened, see #28.

**Comment by mnapoli** [comment]
Maybe there is a regression with 1.5.0 but it's bringing out a real problem: the method will be called statically here unless there is a DI container configured (and one that supports autowiring on top of it).

I've had a second report of this from someone who expected classes to be magically instantiated too (no DI container configured).

Maybe what could be done (on top of #28) is throw an explicit exception is it's not a valid callable (`['MyApp\Command\ScanCommand', 'execute']` is not because it's not a static method, even though PHP accepts it in `callable` type-hints). If the exception has a clear error message it could be helpful, e.g.:

> ['MyApp\Command\ScanCommand', 'execute'] is not a callable because `execute` is a static method. Either use [new MyApp\Command\ScanCommand(), 'execute'] or configure a dependency injection container that supports autowiring like PHP-DI.

@thecrypticace see https://github.com/PHP-DI/Invoker/blob/master/src/CallableResolver.php#L90-L96 and https://github.com/PHP-DI/Invoker/blob/master/src/CallableResolver.php#L110-L126 for example, that's what I do in `Invoker`. Actually I'm not even sure why there's no exception thrown currently because we are using the Invoker, so it should throw one…

**Comment by mnapoli** [comment]
Oh I think I get it, that's because when there is no container configured there is no `CallableResolver` created so the verification is not done, and it uses `is_callable` which accepts the invalid callable: https://github.com/PHP-DI/Invoker/blob/master/src/Invoker.php#L56

**Comment by mnapoli** [comment]
I have added a test covering this bug in #29 WDYT?

**Comment by thecrypticace** [comment]
That looks good to me. Question regarding the CallableResolver, would it make sense to raise the access level of the code there to allow it to be used elsewhere or just duplicate it here?

**Comment by mnapoli** [comment]
I think we can duplicate it here for now.
